env:
  es6: true
extends:
  - 'eslint:recommended'
  - standard
parser: 'babel-eslint'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module

rules:
  semi:
    - error
    - always
  quotes:
    - error
    - single